sudo: false

language: scala

jdk: openjdk10

scala:
  - 2.12.8

branches:
  only:
    - master

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalafmtCheck scalafmtSbtCheck

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
